language: cpp
compiler:
  - clang
  - gcc
before_install:
# nomlib dependencies (SDL, OpenAL, libsndfile, libmagic, GTK)
  - echo "y" | sudo add-apt-repository ppa:zoogie/sdl2
  - sudo apt-get update
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsndfile1-dev libopenal-dev # doxygen graphviz
before_script:
  - mkdir -p build && cd build
  - cmake -D CMAKE_VERBOSE_MAKEFILE=on -D EXAMPLES=on -D CMAKE_INSTALL_PREFIX=/usr/local ..
script:
  - make -j4
  - sudo make install
  - du -csh /usr/local/lib/libnomlib.*
  - du -csh /usr/local/share/nomlib/
  - du -csh /usr/local/share/doc/nomlib/
  - sudo make uninstall
  - make clean
# whitelist
branches:
  only:
    - travis
    #- dev
    #- master
