language: cpp
compiler:
  - clang
  - gcc
before_install:
# nomlib dependencies (SDL)
  - sudo apt-get install libsdl1.2-dev libsdl1.2debian libsdl-image1.2-dev libsdl-image1.2 libsdl-ttf2.0-dev libsdl-ttf2.0-0
# nomlib dependencies (Audio)
  - sudo apt-get install libsndfile1-dev libopenal-dev
# nomlib dependencies (misc)
  - sudo apt-get install libmagic-dev #doxygen graphviz #libjson-spirit-dev
# nomlib dependencies (platform)
  - sudo apt-get install libgtk2.0-dev
before_script:
  - mkdir -p build build-osx && cd build
  - cmake -DVERBOSE=on -D DOCS=off -D EXAMPLES=on ..
script:
  - make -j4
  - sudo make install
  - sudo make uninstall
  - make clean
# whitelist
branches:
  only:
    - dev
    - master
