language: cpp
compiler:
  - clang
  - gcc
before_install:
# nomlib dependencies (SDL)
  - sudo apt-get install libsdl1.2-dev libsdl1.2debian libsdl-image1.2-dev libsdl-image1.2 libsdl-ttf2.0-dev libsdl-ttf2.0-0
# nomlib dependencies (Audio)
  - sudo apt-get install libsndfile1-dev libopenal-dev
before_script:
  - mkdir -p build && cd build && cmake ..
script:
  - make -j4
  - sudo make install
  - sudo make uninstall
# whitelist
branches:
  only:
    - dev

