language: cpp
compiler:
  - clang
  - gcc
before_install:
# nomlib dependencies (SDL, OpenAL, libsndfile, libmagic, GTK)
  - sudo apt-get install libsdl1.2-dev libsdl1.2debian libsdl-image1.2-dev libsdl-image1.2 libsdl-ttf2.0-dev libsdl-ttf2.0-0 libsndfile1-dev libopenal-dev libmagic-dev libgtk2.0-dev #doxygen graphviz #libjson-spirit-dev
before_script:
  - mkdir -p build build-osx && cd build
  - cmake -DVERBOSE=on -D DOCS=off -D EXAMPLES=on ..
script:
  - make -j4
  - sudo make install
  - sudo make uninstall
  - make clean
# whitelist
branches:
  only:
    - dev
    - master
